version: '3.9'
services:
  php:
    container_name: docker_symfony
    build:
      context: ./
      target: "base"
    command: "symfony server:start"
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"